version: '2'
services:
  postgres:
      container_name: t_postgres
      image: postgres:11.2
      volumes:
          - postgresvolume:/var/lib/postgresql/data
      environment:
          - POSTGRES_DB=test
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=TWq6zVfy6WejdJ3THMJS
  nginx_backend:
      container_name: t_nginx_backend
      build:
          dockerfile: ./Dockerfile
          args:
            - ENVIRONMENT=local
          context: containers/nginx_backend
      volumes:
          - ./logs/nginx:/etc/logs/nginx
      volumes_from:
          - backend
      links:
          - backend
  backend:
      container_name: t_backend
      build:
          dockerfile: ./Dockerfile
          context: ./containers/backend
          args:
              - ENVIRONMENT=local
      volumes:
          - ./apps/backend/:/var/www
      links:
          - postgres
  nginx_frontend:
      container_name: t_nginx_front
      build:
          dockerfile: ./Dockerfile
          args:
              - ENVIRONMENT=local
          context: containers/nginx_frontend
      ports:
          - 8080:8080
      volumes:
          - ./logs/nginx:/etc/logs/nginx
      volumes_from:
          - frontend
      links:
          - frontend
  frontend:
      container_name: t_frontend
      build:
          dockerfile: ./Dockerfile
          context: ./containers/frontend
          args:
              - ENVIRONMENT=local
      volumes:
          - ./apps/frontend/:/var/www
      links:
          - nginx_backend
volumes:
  postgresvolume: